package io.github.xblocker

import android.os.Binder
import android.os.IBinder
import android.os.Looper
import android.os.Parcel
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import io.github.xblocker.data.XposedServiceClient
import org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.Properties
import java.util.zip.ZipFile

/** Wire contract checked against Java generated by the Android AIDL compiler. */
@RunWith(AndroidJUnit4::class)
class XposedScopeTest {
    private val descriptor = "io.github.libxposed.service.IXposedService"
    private val callbackDescriptor = "io.github.libxposed.service.IXposedScopeCallback"
    private val packages = listOf("com.twitter.android", "com.android.systemui")

    @Test fun apkDeclaresDynamicModernScopeAndRetainsLegacyEntry() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        ZipFile(context.applicationInfo.sourceDir).use { apk ->
            val props = Properties().apply {
                apk.getInputStream(apk.getEntry("META-INF/xposed/module.prop")).use(::load)
            }
            assertEquals("101", props.getProperty("minApiVersion"))
            assertEquals("101", props.getProperty("targetApiVersion"))
            assertEquals("false", props.getProperty("staticScope"))
            val entry = apk.getInputStream(apk.getEntry("META-INF/xposed/java_init.list"))
                .bufferedReader().use { it.readText().trim() }
            assertEquals("io.github.xblocker.hook.ModernXHook", entry)
            assertNotNull(apk.getEntry("assets/xposed_init"))
        }
    }

    @Test fun readsGrantedScopeWithAidlTransactionCode() {
        XposedServiceClient.onBinder(object : Binder() {
            override fun onTransact(code: Int, data: Parcel, reply: Parcel?, flags: Int): Boolean {
                if (code != IBinder.FIRST_CALL_TRANSACTION + 10) return false
                data.enforceInterface(descriptor)
                requireNotNull(reply).writeNoException()
                reply.writeStringList(packages)
                return true
            }
        })
        assertEquals(packages, XposedServiceClient.scope())
    }

    @Test fun requestTransmitsCallbackAndDeliversApprovalOnMainThread() = requestResult(true)
    @Test fun requestDeliversDenialOnMainThread() = requestResult(false)

    private fun requestResult(approve: Boolean) {
        var received: List<String>? = null
        var callback: IBinder? = null
        XposedServiceClient.onBinder(object : Binder() {
            override fun onTransact(code: Int, data: Parcel, reply: Parcel?, flags: Int): Boolean {
                if (code != IBinder.FIRST_CALL_TRANSACTION + 11) return false
                data.enforceInterface(descriptor)
                assertEquals(IBinder.FLAG_ONEWAY, flags)
                received = data.createStringArrayList()
                callback = data.readStrongBinder()
                assertEquals(0, data.dataAvail())
                return true
            }
        })
        val done = CountDownLatch(1)
        var approved: List<String>? = null
        var error: String? = null
        var onMain = false
        XposedServiceClient.requestScope(packages) { result, failure ->
            approved = result
            error = failure
            onMain = Looper.myLooper() == Looper.getMainLooper()
            done.countDown()
        }
        assertEquals("The framework must receive the requested packages", packages, received)
        assertNotNull("The request must include a callback binder", callback)
        val data = Parcel.obtain()
        try {
            data.writeInterfaceToken(callbackDescriptor)
            if (approve) data.writeStringList(packages) else data.writeString("Request denied by user")
            assertTrue(callback!!.transact(IBinder.FIRST_CALL_TRANSACTION + if (approve) 1 else 2,
                data, null, IBinder.FLAG_ONEWAY))
        } finally { data.recycle() }
        assertTrue("Framework result must reach the UI", done.await(3, TimeUnit.SECONDS))
        assertTrue(onMain)
        if (approve) {
            assertEquals(packages, approved)
            assertNull(error)
        } else {
            assertNull(approved)
            assertEquals("Request denied by user", error)
        }
    }

    @Test fun unsupportedRequestReportsSendFailure() {
        XposedServiceClient.onBinder(object : Binder() {
            override fun onTransact(code: Int, data: Parcel, reply: Parcel?, flags: Int) = false
        })
        val done = CountDownLatch(1)
        var error: String? = null
        XposedServiceClient.requestScope(packages) { _, failure -> error = failure; done.countDown() }
        assertTrue(done.await(3, TimeUnit.SECONDS))
        assertEquals("请求发送失败", error)
    }
}
